#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"
logging.level.org.goafabric: "INFO"

logging.level.dev.langchain4j: "DEBUG"
logging.level.dev.ai4j.openai4j: "DEBUG"

spring.profiles.active: "ollama"
#spring.profiles.active: "openai"
#spring.profiles.active: "mock"

#logging.level.org.hibernate.SQL: "DEBUG"